name: faketify
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  flutter_dotenv: ^5.1.0
  flutter_slidable: ^3.0.1
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  rxdart: ^0.27.7
  cached_network_image: ^3.3.1
  audio_video_progress_bar: ^2.0.1
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.1
  dio: ^5.4.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
  - .env
  - assets/images/
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
